CREATE TABLE housingdata (
	"Year" integer,
	"Before Tax Change" text,
	"Current residence in" text,
	"Total Population" bigint,
	"Same house 1 year ago" bigint,
	"Same state of residence 1 year ago" bigint,
	"Total_Incoming" bigint,
	"Total_Outgoing" bigint,
	"Net Migration" bigint,
	"Net Migrationpn"	text,
	"Avg Home Price" bigint,
	"Median Income" bigint,
	"Unemployment Rate" bigint,
	"Alabama"	bigint,
	"Alaska" bigint,
	"Arizona" bigint,
	"Arkansas" bigint,
	"California" bigint,
	"Colorado" bigint,
	"Connecticut" bigint,
	"Delaware" bigint,
	"DistrictColumbia " bigint,
	"Florida" bigint,
	"Georgia" bigint,
	"Hawaii" bigint,
	"Idaho" bigint,
	"Illinois" bigint,
	"Indiana" bigint,
	"Iowa" bigint,
	"Kansas" bigint,
	"Kentucky" bigint,
	"Louisiana" bigint,
	"Maine" bigint,
	"Maryland" bigint,
	"Massachusetts" bigint,
	"Michigan" bigint,
	"Minnesota" bigint,
	"Mississippi" bigint,
	"Missouri" bigint,
	"Montana" bigint,
	"Nebraska" bigint,
	"Nevada" bigint,
	"New Hampshire" bigint,
	"New Jersey" bigint,
	"New Mexico" bigint,
	"New York" bigint,
	"North Carolina" bigint,
	"North Dakota" bigint,
	"Ohio" bigint,
	"Oklahoma" bigint,
	"Oregon" bigint,
	"Pennsylvania" bigint,
	"Rhode Island" bigint,
	"South Carolina" bigint,
	"South Dakota" bigint,
	"Tennessee" bigint,
	"Texas" bigint,
	"Utah" bigint,
	"Vermont" bigint,
	"Virginia" bigint,
	"Washington" bigint,
	"West Virginia" bigint,
	"Wisconsin" bigint,	
	"Wyoming" bigint,
	"Puerto Rico" bigint,
	"US Island Area" bigint,	
	"Foreign Country" bigint

	
);